"""Changes

Revision ID: b80304c049a2
Revises: 
Create Date: 2025-09-06 15:38:58.269037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80304c049a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_api_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('api_secret', sa.String(length=255), nullable=True),
    sa.Column('db_host', sa.String(length=255), nullable=False),
    sa.Column('db_port', sa.Integer(), nullable=False),
    sa.Column('db_name', sa.String(length=100), nullable=False),
    sa.Column('db_username', sa.String(length=100), nullable=False),
    sa.Column('db_password', sa.String(length=500), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_api_configs')
    # ### end Alembic commands ###
